### ISSUE TITLE
BLUEs from H2cal may be wrong if other fixed effects in the model

### ISSUE THREAD

**Issue by ncsumaize** [Flavjack/inti#10]
I fit a model in H2cal that included genotypes but another fixed effect, which I put last in the model. When you do that, this slicing operation gets the wrong rows for the blues data frame:

dplyr::slice((count+1):NROW(.))  

In my example, count = 1, but in the fef() output, the other fixed effect is last in the list, so this slicing skips the first genotype and includes the other fixed effect. Workaround is easy for me, just change the order of the terms in the model, but you may want to consider grepping for the geno.name in the fef() output to get the correct indices for slicing to make it more robust.

Just found your package today and think it's awesome, thanks - Jim Holland james_holland@ncsu.edu

**Comment by Flavjack** [comment]
Dear Jim Holland, many thanks for the suggestions and I appreciate your time to check the code. I updated the function grepping the geno.names. Now it is available in the dev. version
If you have further suggestions to improve the function, please let me know.
Flavio Lozano <flozano@lamolina.edu.pe>
