### ISSUE TITLE
Blues vs BLUPs

### ISSUE THREAD

**Issue by elcansaito** [Flavjack/inti#15]
I am running this code.

a = H2cal(data = Data,
           trait = "drymatter",
           gen.name = "Line",
           env.n = 2, year.n = 2,rep.n = 2,
           env.name = "Loc",
           #emmeans = TRUE,
           year.name = "Year", # 1 is intercept
           outliers.rm=TRUE,
           fixed.model = "1+Line+(1|Loc)+(1|Year)+(1|Line:Loc)+(1|Line:Year)+(1|Line:Loc:Year)",
           random.model = "1+(1|Line)+(1|Loc)+(1|Year)+(1|Line:Loc)+(1|Line:Year)+(1|Line:Loc:Year)") 

and when I look at the BLUES and BLUPs, I observed the attached picture results. 

So my question is, if BLUPs are predictions of random effects, and they should be centered around zero. BLUEs are for fixed effects, and they are not necessarily centered at zero. Nevertheless,  how in the results A$Blups, looks like BLues and A$BLUES looks like BLUPs. A$BLUES have even the smith for the calculation of heritability. Am I right? Is this an error in nomenclature in the package? 
![ISSUE](https://github.com/user-attachments/assets/989a875d-1b3a-4dc7-9976-c5c9aa4ed4fd)
Thanks for any feedback.

**Comment by Flavjack** [comment]
Perfect, thanks for writing the answer.
